"$schema" = 'https://starship.rs/config-schema.json'

# [ ░▒▓](#a3aed2)\
# [ 󰣇 ](bg:#a3aed2 fg:#090c0c)\
# [](bg:#769ff0 fg:#a3aed2)\
format = """
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#1d2230)\
[ ](fg:#1d2230)\
$character
"""

right_format = """
[◖](fg:#1d2230)\
$time\
[◗](fg:#1d2230)\
"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path]($style)"
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = true

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind)](fg:#769ff0 bg:#394260)]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#a0a9cb bg:#1d2230"
format = '[$time]($style)'

[character]
success_symbol = '[❯](bold fg:#a3aed2)'