[mgr]
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true
linemode = "size"
show_hidden = true
show_symlink = true
scrolloff = 3
mouse_events = ["click", "scroll"]

[preview]
wrap = "no"
tab_size = 2
image_delay = 100
image_filter = "triangle"
image_quality = 80

[input]
cursor_blink = true